title: Interview Questions
description: Interview Questions and their solutions. Contains solutions of quality questions asked in interviews.
iconURL: assets/img/global/geek-paradox-transparent.png

markdown: kramdown

# for a clean URL
permalink: :slug

social:
  twitter: evilj0ker19
  github: rajat19

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections_dir: posts

collections:
  questions:
    title: Interview Question
    output: true
    sort_by: title
  # hard:
  #   title: Leetcode Hard
  #   output: true
  #   sort_by: leetid
  # medium:
  #   title: Leetcode Medium
  #   output: true
  #   sort_by: leetid
#  fb:
#    title: Facebook Recruiting Practice
#    output: true

header_pages:
  - hello-world.md