title: Interview Questions
iconURL: assets/img/among_us.svg

markdown: kramdown

# for a clean URL
permalink: :slug

social:
  twitter: evilj0ker19
  github: rajat19

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections_dir: posts

collections:
  hard:
    output: true
    sort_by: leetid
  medium:
    output: true
    sort_by: leetid

header_pages:
  - hello-world.md