title: Interview Questions
iconURL: assets/img/among_us.svg

markdown: kramdown

# for a clean URL
permalink: :slug

social:
  twitter: evilj0ker19
  github: rajat19

plugins:
  - jekyll-feed
  - jekyll-seo-tag

enabled_languages: java

lang_map:
  - name: C
    ext: c
  - name: C++
    ext: cpp
  - name: C#
    ext: cs
  - name: Golang
    ext: go
  - name: Java
    ext: java
  - name: Javascript
    ext: js
  - name: Kotlin
    ext: kt
  - name: PHP
    ext: php
  - name: Python
    ext: py
  - name: Ruby
    ext: rb
  - name: Rust
    ext: rust
  - name: Scala
    ext: scala

collections_dir: posts

collections:
  hard:
    output: true
    sort_by: leetid
  medium:
    output: true
    sort_by: leetid
  sample:
    output: true